[project]
name = "team5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "s1f10240295", email = "s1f102402956@iniad.org" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.2",
]

[project.scripts]
team5 = "team5:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
